---
title: "Plot Alpha"
output: rmarkdown::github_document
---

# Introduction #

This RMarkdown document describes reading  a netCDF file consisting of several bioclimatic variables, and plots one of them `alpha`

## Load packages ## 

```{r}
# load packages
library(maptools) # also loads sp package
library(raster)
library(rasterVis)
library(RColorBrewer)
```

## Read data ##

### Shapefile ###

Read a shapefile, for plotting maps later.

```{r}
# read a world shapefile
shp_path <- "/Users/bartlein/Projects/ESSD/data/shp_files/"
shp_name <- "world2012.shp" 
shp_file <- paste(shp_path, shp_name, sep="")
world.shp <- readShapeLines(shp_file,proj4string=CRS("+proj=longlat"))

# plot the shape file
plot(world.shp, col="gray", lwd=1)
```

### Data ###

Now read in alpha.

```{r}
# read alpha (AE/PE)
alpha_path <- "/Users/bartlein/Projects/ESSD/data/nc_files/"
alpha_name <- "cru10min30_bio.nc"
alpha_file <- paste(alpha_path, alpha_name, sep="")
alpha <- raster(alpha_file, varname="mipt")
alpha
```

## Plot the data ##

Finally, plot alpha using the `levelplot()` function from `rasterVis`:

```{r}
# rasterVis plot
mapTheme <- rasterTheme(region=brewer.pal(8,"BrBG"))
plt <- levelplot(alpha, margin=F, par.settings=mapTheme, main="AE/PE")
plt + layer(sp.lines(world.shp, col="gray", lwd=0.5))
```
